import { Map } from "immutable";

let mapGame = [
  [
    { land: "empty", position: "0:0" },
    { land: "empty", position: "0:1" },
    { land: "empty", position: "0:2" },
    { land: "empty", position: "0:3" },
    { land: "empty", position: "0:4" },
    { land: "empty", position: "0:5" },
    { land: "empty", position: "0:6" },
    { land: "empty", position: "0:7" },
    { land: "empty", position: "0:8" },
    { land: "empty", position: "0:9" },
    { land: "empty", position: "0:10" },
  ],
  [
    { land: "mountain", position: "1:0" },
    { land: "mountain", position: "1:1" },
    { land: "empty", position: "1:2" },
    { land: "empty", position: "1:3" },
    { land: "desert", position: "1:4" },
    { land: "empty", position: "1:5" },
    { land: "ruin", position: "1:6" },
    { land: "forest", position: "1:7", locked: true },
    { land: "empty", position: "1:8" },
    { land: "empty", position: "1:9" },
    { land: "empty", position: "1:10" },
  ],
  [
    { land: "empty", position: "2:0" },
    { land: "desert", position: "2:1" },
    { land: "empty", position: "2:2" },
    { land: "mountain", position: "2:3" },
    { land: "empty", position: "2:4" },
    { land: "empty", position: "2:5" },
    { land: "empty", position: "2:6" },
    { land: "empty", position: "2:7" },
    { land: "ruin", position: "2:8" },
    { land: "lake", position: "2:9", locked: true },
    { land: "empty", position: "2:10" },
  ],
  [
    { land: "desert", position: "3:0" },
    { land: "empty", position: "3:1" },
    { land: "empty", position: "3:2" },
    { land: "empty", position: "3:3" },
    { land: "empty", position: "3:4" },
    { land: "empty", position: "3:5" },
    { land: "empty", position: "3:6" },
    { land: "empty", position: "3:7" },
    { land: "empty", position: "3:8" },
    { land: "empty", position: "3:9" },
    { land: "empty", position: "3:10" },
  ],
  [
    { land: "empty", position: "4:0" },
    { land: "empty", position: "4:1" },
    { land: "empty", position: "4:2" },
    { land: "empty", position: "4:3" },
    { land: "empty", position: "4:4" },
    { land: "empty", position: "4:5" },
    { land: "empty", position: "4:6" },
    { land: "desert", position: "4:7" },
    { land: "empty", position: "4:8" },
    { land: "empty", position: "4:9" },
    { land: "empty", position: "4:10" },
  ],
  [
    { land: "empty", position: "5:0" },
    { land: "empty", position: "5:1" },
    { land: "empty", position: "5:2" },
    { land: "empty", position: "5:3" },
    { land: "empty", position: "5:4" },
    { land: "empty", position: "5:5" },
    { land: "ruin", position: "5:6" },
    { land: "empty", position: "5:7" },
    { land: "empty", position: "5:8" },
    { land: "empty", position: "5:9" },
    { land: "empty", position: "5:10" },
  ],
  [
    { land: "desert", position: "6:0" },
    { land: "ruin", position: "6:1" },
    { land: "empty", position: "6:2" },
    { land: "empty", position: "6:3" },
    { land: "ruin", position: "6:4" },
    { land: "mountain", position: "6:5" },
    { land: "desert", position: "6:6" },
    { land: "empty", position: "6:7" },
    { land: "empty", position: "6:8" },
    { land: "empty", position: "6:9" },
    { land: "ruin", position: "6:10" },
  ],
  [
    { land: "desert", position: "7:0" },
    { land: "empty", position: "7:1" },
    { land: "mountain", position: "7:2" },
    { land: "mountain", position: "7:3" },
    { land: "ruin", position: "7:4" },
    { land: "empty", position: "7:5" },
    { land: "empty", position: "7:6" },
    { land: "empty", position: "7:7" },
    { land: "mountain", position: "7:8" },
    { land: "empty", position: "7:9" },
    { land: "empty", position: "7:10" },
  ],
  [
    { land: "empty", position: "8:0" },
    { land: "empty", position: "8:1" },
    { land: "ruin", position: "8:2" },
    { land: "empty", position: "8:3" },
    { land: "empty", position: "8:4" },
    { land: "ruin", position: "8:5" },
    { land: "empty", position: "8:6" },
    { land: "desert", position: "8:7" },
    { land: "empty", position: "8:8" },
    { land: "empty", position: "8:9" },
    { land: "desert", position: "8:10" },
  ],
  [
    { land: "empty", position: "9:0" },
    { land: "empty", position: "9:1" },
    { land: "empty", position: "9:2" },
    { land: "empty", position: "9:3" },
    { land: "empty", position: "9:4" },
    { land: "empty", position: "9:5" },
    { land: "mountain", position: "9:6" },
    { land: "empty", position: "9:7" },
    { land: "empty", position: "9:8" },
    { land: "empty", position: "9:9" },
    { land: "empty", position: "9:10" },
  ],
  [
    { land: "mountain", position: "10:0" },
    { land: "empty", position: "10:1" },
    { land: "empty", position: "10:2" },
    { land: "empty", position: "10:3" },
    { land: "empty", position: "10:4" },
    { land: "empty", position: "10:5" },
    { land: "ruin", position: "10:6" },
    { land: "desert", position: "10:7" },
    { land: "empty", position: "10:8" },
    { land: "mountain", position: "10:9" },
    { land: "empty", position: "10:10" },
  ],
];

var Mock = {
  rooms: [
    {
      name: "gagaga",
      locked: false,
      map: [],
      round: [],
    },
  ],
  players: [
    [
      {
        roomReady: true,
        socketId: "5aJjkVUzkUkCsRfAAAAb",
        authenticated: true,
        score: 0,
        roundReady: false,
        inGame: true,
        room: "tyty",
        map: mapGame,
        pseudo: "UnicornBuster",
      },
      {
        roomReady: true,
        socketId: "5aJjkVUzkUkCsRfAAA5Ab",
        authenticated: true,
        score: 0,
        roundReady: false,
        inGame: true,
        room: "tyty",
        map: mapGame,
        pseudo: "PoneyMan",
      },
      {
        roomReady: true,
        socketId: "5aJjkVUzkUkCsRfAA2AAb",
        authenticated: true,
        score: 0,
        roundReady: false,
        inGame: true,
        room: "tyty",
        map: mapGame,
        pseudo: "UnicornBlaster",
      },
    ],
  ],
  player: new Map({
    roomReady: true,
    socketId: "5aJjkVUzkUkCsRfAAAAb",
    authenticated: true,
    score: 0,
    roundReady: false,
    inGame: true,
    room: "tyty",
    map: mapGame,
    pseudo: "UnicornBuster",
  }),
  otherPlayers: [
    {
      roomReady: true,
      socketId: "5aJjkVUzkUkCsRfAAA5Ab",
      authenticated: true,
      score: 0,
      roundReady: false,
      inGame: true,
      room: "tyty",
      map: mapGame,
      pseudo: "PoneyMan",
    },
    {
      roomReady: true,
      socketId: "5aJjkVUzkUkCsRfAA2AAb",
      authenticated: true,
      score: 0,
      roundReady: false,
      inGame: true,
      room: "tyty",
      map: mapGame,
      pseudo: "UnicornBlaster",
    },
  ],
  round: {
    season: 0,
    number: 0,
    piece: {
      size: 3,
      availableLands: ["forest", "lake"],
      shape: [1, 0, 0, 1, 1, 0, 0, 1, 1],
    },
  },
  room: {
    name: "tyty",
    locked: false,
    map: mapGame,
    round: {
      season: 0,
      number: 0,
      piece: {
        size: 3,
        availableLands: ["forest", "lake"],
        shape: [1, 0, 0, 1, 1, 0, 0, 1, 1],
      },
    },
    players: [
      {
        roomReady: true,
        socketId: "5aJjkVUzkUkCsRfAAAAb",
        authenticated: true,
        score: 0,
        roundReady: false,
        inGame: true,
        room: "tyty",
        map: mapGame,
        pseudo: "UnicornBuster",
      },
      {
        roomReady: true,
        socketId: "5aJjkVUzkUkCsRfAAA5Ab",
        authenticated: true,
        score: 0,
        roundReady: false,
        inGame: true,
        room: "tyty",
        map: mapGame,
        pseudo: "PoneyMan",
      },
      {
        roomReady: true,
        socketId: "5aJjkVUzkUkCsRfAA2AAb",
        authenticated: true,
        score: 0,
        roundReady: false,
        inGame: true,
        room: "tyty",
        map: mapGame,
        pseudo: "UnicornBlaster",
      },
    ],
  },
};

export default Mock;
